import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import web_server_base
from esphome.const import CONF_ID, CONF_PORT
import gzip
import os

DEPENDENCIES = ["wifi", "web_server_base"]
AUTO_LOAD = ["web_server_base", "json", "network"]
CODEOWNERS = ["@mahipat99"]

web_server_ns = cg.esphome_ns.namespace("web_server_custom")
WebServerCustom = web_server_ns.class_("WebServerCustom", cg.Component)

# ── Stubs required by ESPHome entity components ───────────────────────────────
WEBSERVER_SORTING_SCHEMA = cv.Schema({
    cv.Optional("web_server_sorting_weight"): cv.float_,
})
CONF_WEB_SERVER_SORTING_WEIGHT = "web_server_sorting_weight"
CONF_WEB_SERVER = "web_server"

def add_entity_config(var, config):
    pass

async def add_entity_config_async(var, config):
    pass

# ── Config schema ─────────────────────────────────────────────────────────────
CONFIG_SCHEMA = cv.Schema(
    {
        cv.GenerateID(): cv.declare_id(WebServerCustom),
        cv.Optional(CONF_PORT, default=80): cv.port,
        cv.Optional("auth_username", default=""): cv.string,
        cv.Optional("auth_password", default=""): cv.string,
    }
).extend(cv.COMPONENT_SCHEMA)


def _embed_frontend():
    www_dir = os.path.join(os.path.dirname(__file__), "www")
    html_path = os.path.join(www_dir, "index.html")

    if not os.path.exists(html_path):
        raise FileNotFoundError(f"Frontend not found at {html_path}")

    with open(html_path, "rb") as f:
        raw = f.read()

    compressed = gzip.compress(raw, compresslevel=9)

    lines = [
        "// Auto-generated by ESPHome __init__.py — do not edit manually",
        "#pragma once",
        "",
        "// PROGMEM is Arduino-only; define as empty on IDF",
        "#ifndef PROGMEM",
        "#define PROGMEM",
        "#endif",
        "",
        f"// Original: {len(raw)} bytes  Gzipped: {len(compressed)} bytes",
        "static const uint8_t WEB_UI_GZ[] PROGMEM = {",
    ]

    chunk = 16
    hex_rows = []
    for i in range(0, len(compressed), chunk):
        row = compressed[i: i + chunk]
        hex_rows.append("  " + ", ".join(f"0x{b:02x}" for b in row))
    lines.append(",\n".join(hex_rows))
    lines.append("};")
    lines.append(f"static const size_t WEB_UI_GZ_LEN = {len(compressed)};")

    out_path = os.path.join(os.path.dirname(__file__), "web_ui_data.h")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[web_server] Embedded frontend: {len(raw)}B → {len(compressed)}B gzipped")


async def to_code(config):
    _embed_frontend()

    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)

    cg.add(var.set_port(config[CONF_PORT]))

    if config["auth_username"]:
        cg.add(var.set_auth(config["auth_username"], config["auth_password"]))

    from esphome.core import CORE
    if CORE.is_esp32:
        cg.add_define("USE_ESP_IDF")

    cg.add_define("USE_WEBSERVER_CUSTOM")
