#!/usr/bin/env python3
"""
generate_embedded_html.py
─────────────────────────
Standalone helper to (re)generate web_ui_data.h from www/index.html.
"""

import argparse
import gzip
import os
import sys
from datetime import datetime, timezone


# ✅ NEW: preprocess HTML before compression
def process_html(raw: bytes) -> bytes:
    html = raw.decode("utf-8")

    # Fix title flash
    html = html.replace(
        "<title>ESPHome</title>",
        "<title>Loading...</title>"
    )

    # Inject early JS (runs before UI loads)
    inject = """
<script>
(function() {
  try {
    const name = window.location.hostname || "Device";
    document.title = name;
  } catch (e) {}
})();
</script>
"""

    html = html.replace("</head>", inject + "\n</head>")

    return html.encode("utf-8")


def generate(input_path: str, output_path: str) -> None:
    if not os.path.exists(input_path):
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    with open(input_path, "rb") as f:
        raw = f.read()

    # ✅ Apply preprocessing
    processed = process_html(raw)

    compressed = gzip.compress(processed, compresslevel=9)
    ratio = len(compressed) / len(processed) * 100

    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [
        f"// Auto-generated by generate_embedded_html.py on {now}",
        "// DO NOT EDIT — regenerate with: python generate_embedded_html.py",
        "",
        "#pragma once",
        "#ifdef ARDUINO",
        "#include <pgmspace.h>",
        "#else",
        "#define PROGMEM",
        "#endif",
        "",
        f"// Source : {os.path.basename(input_path)}",
        f"// Raw    : {len(processed):,} bytes",
        f"// Gzipped: {len(compressed):,} bytes ({ratio:.1f}% of original)",
        "",
        "static const uint8_t WEB_UI_GZ[] PROGMEM = {",
    ]

    chunk = 16
    rows = []
    for i in range(0, len(compressed), chunk):
        row = compressed[i : i + chunk]
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in row))
    lines.append(",\n".join(rows))
    lines.append("};")
    lines.append(f"static const size_t WEB_UI_GZ_LEN = {len(compressed)};")
    lines.append("")

    content = "\n".join(lines)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(
        f"[generate_embedded_html] "
        f"{len(processed):,} B → {len(compressed):,} B gzipped "
        f"({ratio:.1f}%)  →  {output_path}"
    )


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    default_input = os.path.join(here, "www", "index.html")
    default_output = os.path.join(here, "web_ui_data.h")

    parser = argparse.ArgumentParser(description="Embed SPA into a C header.")
    parser.add_argument("--input",  default=default_input,  help="Path to index.html")
    parser.add_argument("--output", default=default_output, help="Path to output .h file")
    args = parser.parse_args()

    generate(args.input, args.output)


if __name__ == "__main__":
    main()